/* Generated By:JavaCC: Do not edit this line. JUSTTreeConstants.java Version 5.0 */
package javacc;

public interface JUSTTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCOMPILATIONUNIT = 1;
  public int JJTDEFINITION = 2;
  public int JJTVARDEF = 3;
  public int JJTINIT = 4;
  public int JJTTYPE = 5;
  public int JJTFUNCDEF = 6;
  public int JJTFUNCHEAD = 7;
  public int JJTFORMPARLIST = 8;
  public int JJTBLOCK = 9;
  public int JJTSTAT = 10;
  public int JJTASSIGNSTAT = 11;
  public int JJTCALLSTAT = 12;
  public int JJTCALL = 13;
  public int JJTACTPARLIST = 14;
  public int JJTIFSTAT = 15;
  public int JJTWHILESTAT = 16;
  public int JJTRETURNSTAT = 17;
  public int JJTEXPR = 18;
  public int JJTOREXPR = 19;
  public int JJTANDEXPR = 20;
  public int JJTRELEXPR = 21;
  public int JJTSIMPLEEXPR = 22;
  public int JJTTERM = 23;
  public int JJTNOTFACT = 24;
  public int JJTFACT = 25;


  public String[] jjtNodeName = {
    "Start",
    "CompilationUnit",
    "Definition",
    "VarDef",
    "Init",
    "Type",
    "FuncDef",
    "FuncHead",
    "FormParList",
    "Block",
    "Stat",
    "AssignStat",
    "CallStat",
    "Call",
    "ActParList",
    "IfStat",
    "WhileStat",
    "ReturnStat",
    "Expr",
    "OrExpr",
    "AndExpr",
    "RelExpr",
    "SimpleExpr",
    "Term",
    "NotFact",
    "Fact",
  };
}
/* JavaCC - OriginalChecksum=78ea203eb613f883f5ced1fae6bce381 (do not edit this line) */
