/* Generated By:JJTree&JavaCC: Do not edit this line. JUSTConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JUSTConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 7;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 8;
  /** RegularExpression Id. */
  int HEX_LITERAL = 9;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 10;
  /** RegularExpression Id. */
  int Number = 11;
  /** RegularExpression Id. */
  int PROGRAM = 12;
  /** RegularExpression Id. */
  int VoidType = 13;
  /** RegularExpression Id. */
  int IntType = 14;
  /** RegularExpression Id. */
  int BooleanType = 15;
  /** RegularExpression Id. */
  int byref = 16;
  /** RegularExpression Id. */
  int If = 17;
  /** RegularExpression Id. */
  int Else = 18;
  /** RegularExpression Id. */
  int While = 19;
  /** RegularExpression Id. */
  int Return = 20;
  /** RegularExpression Id. */
  int TrueValue = 21;
  /** RegularExpression Id. */
  int FalseValue = 22;
  /** RegularExpression Id. */
  int IDENTIFIER = 23;
  /** RegularExpression Id. */
  int LETTER = 24;
  /** RegularExpression Id. */
  int DIGIT = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<Number>",
    "\"program\"",
    "\"void\"",
    "\"int\"",
    "\"boolean\"",
    "\"byref\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"!\"",
  };

}
