/* Generated By:JavaCC: Do not edit this line. JUSTCompilerTreeConstants.java Version 5.0 */
package grammar;

public interface JUSTCompilerTreeConstants
{
  public int JJTSTART = 0;
  public int JJTONE_LINE = 1;
  public int JJTCOMPILATIONUNIT = 2;
  public int JJTDEFINITION = 3;
  public int JJTVARDEF = 4;
  public int JJTFUNCDEF = 5;
  public int JJTTYPE = 6;
  public int JJTBLOCK = 7;
  public int JJTSTAT = 8;
  public int JJTASSIGNSTAT = 9;
  public int JJTCALLSTAT = 10;
  public int JJTCALL = 11;
  public int JJTACTPARLIST = 12;
  public int JJTIFSTAT = 13;
  public int JJTWHILESTAT = 14;
  public int JJTRETURNSTAT = 15;
  public int JJTEXPR = 16;
  public int JJTOREXPR = 17;
  public int JJTANDEXPR = 18;
  public int JJTRELEXPR = 19;
  public int JJTSIMPLEEXPR = 20;
  public int JJTTERM = 21;
  public int JJTNOTFACT = 22;
  public int JJTFACT = 23;
  public int JJTCOMPARE = 24;
  public int JJTINIT = 25;
  public int JJTFUNCHEAD = 26;
  public int JJTFORMPARLIST = 27;
  public int JJTFORMPAR = 28;
  public int JJTSUM = 29;


  public String[] jjtNodeName = {
    "Start",
    "one_line",
    "CompilationUnit",
    "Definition",
    "VarDef",
    "FuncDef",
    "Type",
    "Block",
    "Stat",
    "AssignStat",
    "CallStat",
    "Call",
    "ActParList",
    "IfStat",
    "WhileStat",
    "ReturnStat",
    "Expr",
    "OrExpr",
    "AndExpr",
    "RelExpr",
    "SimpleExpr",
    "Term",
    "NotFact",
    "Fact",
    "Compare",
    "Init",
    "FuncHead",
    "FormParList",
    "formPar",
    "sum",
  };
}
/* JavaCC - OriginalChecksum=273bd1299eadfbefc628c0ade4c6b00a (do not edit this line) */
